apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./template/secret.yaml
  - ./template/configmap.yaml
  - ./template/deployment.yaml
  - ./template/service.yaml
  - ./template/pvc.yaml
  - ./template/ingress.yaml
